telegram_token: ""
openai_api_key: ""
claude_api_key: ""
stripe_secret_key: "" 
stripe_webhook_secret: "" # to recieve the payment updates
openai_api_base: null  # leave null to use default api base or you can put your own base url here
allowed_telegram_usernames: []  # if empty, the bot is available to anyone. pass a username string to allow it and/or user ids as positive integers and/or channel ids as negative integers
new_dialog_timeout: 600  # new dialog starts after timeout (in seconds)
return_n_generated_images: 1
n_chat_modes_per_page: 5
image_size: "1024x1024" #Can be configured within the bot menu, its initialized here to have a default
enable_message_streaming: true  # if set, messages will be shown to user word-by-word
developer_username: [""] #will be included in certain errors given to users so they can contact the developer easier
database_timezone: "" #so that the user_roles command give you accurate time of when the users last used the bot

# prices
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006

role_deduction_rates:
  admin: 0
  beta_tester: 1.05
  friend: 0
  regular_user: 1.10
  trial_user: 1

roles:
  admin: [] #add your id here so you have full access to all the commands and unlimited usage(can be found in the database)
  beta_tester: [] 
  friend: [] #unlimited usage of the bot, no admin privileges
  regular_user: []
  trial_user: []
