#available_text_models: ["gpt-3.5-turbo", "gpt-3.5-turbo-16k", "gpt-4-1106-preview", "gpt-4-vision-preview", "gpt-4-turbo-2024-04-09", "gpt-4", "text-davinci-003"] #Big menu
available_text_models: ["gpt-3.5-turbo", "gpt-4-vision-preview", "gpt-4-turbo-2024-04-09"] #small menu with all needed models
available_image_models: ["dalle-2", "dalle-3"]

#prices per 1k tokens or per image, regularly update from openAI's pricing page to be accurate
info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT-16K
    description: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 is the <b>smartest</b> and most advanced model in the world. But it is slower and not as cost-efficient as ChatGPT. Best choice for <b>complex</b> intellectual tasks.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4-1106-preview:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo is a <b>faster</b> and <b>cheaper</b> version of GPT-4. It's as smart as GPT-4, so you should use it instead of GPT-4.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4-vision-preview:
    type: chat_completion
    name: GPT-4 Vision 
    description: Ability to <b>understand images</b>, in addition to all other GPT-4 Turbo capabilties.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  gpt-4-turbo-2024-04-09: #new turbo

    type: chat_completion
    name: GPT-4 Turbo
    description: "GPT-4 Turbo is a <b>faster</b> and <b>cheaper</b> version of GPT-4. It's as smart as GPT-4, so you should use it instead of GPT-4.\n\n This version of turbo is from 09.04.2024."

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: GPT-3.5 is a legacy model. Actually there is <b>no reason to use it</b>, because it is more expensive and slower than ChatGPT, but just about as smart.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
    type: image
    name: DALL-E 2
    description: "<b>DALL-E 2</b> is ideal for generating <b>one</b> or <b>multiple</b> variations of images designs and works quickly with multiple resolution options. Perfect for users seeking results at <b>faster</b> speeds and <b>lower</b> costs."
    resolutions:
      1024x1024:
        price_per_1_image: 0.020
      512x512:
        price_per_1_image: 0.018
      256x256:
        price_per_1_image: 0.016

    scores:
      Quality: 3
      Fast: 4
      Cheap: 4

  dalle-3:
    type: image
    name: DALL-E 3
    description: <b>DALL-E 3</b> provides more <b>detailed</b> and <b>accurate</b> visual generations than DALL-E 2. This model is great for users looking for <b>high-definition</b> images with a variety of quality options.
    qualities:
      standard:
        resolutions:
          1024x1024:
            price_per_1_image: 0.040
          1024x1792:
            price_per_1_image: 0.080
          1792x1024:
            price_per_1_image: 0.080
      hd:
        resolutions:
          1024x1024:
            price_per_1_image: 0.080
          1024x1792:
            price_per_1_image: 0.120
          1792x1024:
            price_per_1_image: 0.120

    scores:
      Quality: 5
      Fast: 3
      Cheap: 2

  whisper:
    type: audio
    price_per_1_min: 0.006